/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiContactRouteImport } from './routes/api.contact'
import { Route as ApiCmsTestimonialsRouteImport } from './routes/api.cms.testimonials'
import { Route as ApiCmsServicesRouteImport } from './routes/api.cms.services'
import { Route as ApiCmsFaqsRouteImport } from './routes/api.cms.faqs'
import { Route as ApiCmsAboutRouteImport } from './routes/api.cms.about'

const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCmsTestimonialsRoute = ApiCmsTestimonialsRouteImport.update({
  id: '/api/cms/testimonials',
  path: '/api/cms/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCmsServicesRoute = ApiCmsServicesRouteImport.update({
  id: '/api/cms/services',
  path: '/api/cms/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCmsFaqsRoute = ApiCmsFaqsRouteImport.update({
  id: '/api/cms/faqs',
  path: '/api/cms/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCmsAboutRoute = ApiCmsAboutRouteImport.update({
  id: '/api/cms/about',
  path: '/api/cms/about',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/api/contact': typeof ApiContactRoute
  '/api/cms/about': typeof ApiCmsAboutRoute
  '/api/cms/faqs': typeof ApiCmsFaqsRoute
  '/api/cms/services': typeof ApiCmsServicesRoute
  '/api/cms/testimonials': typeof ApiCmsTestimonialsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/api/contact': typeof ApiContactRoute
  '/api/cms/about': typeof ApiCmsAboutRoute
  '/api/cms/faqs': typeof ApiCmsFaqsRoute
  '/api/cms/services': typeof ApiCmsServicesRoute
  '/api/cms/testimonials': typeof ApiCmsTestimonialsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/api/contact': typeof ApiContactRoute
  '/api/cms/about': typeof ApiCmsAboutRoute
  '/api/cms/faqs': typeof ApiCmsFaqsRoute
  '/api/cms/services': typeof ApiCmsServicesRoute
  '/api/cms/testimonials': typeof ApiCmsTestimonialsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/api/contact'
    | '/api/cms/about'
    | '/api/cms/faqs'
    | '/api/cms/services'
    | '/api/cms/testimonials'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/api/contact'
    | '/api/cms/about'
    | '/api/cms/faqs'
    | '/api/cms/services'
    | '/api/cms/testimonials'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/api/contact'
    | '/api/cms/about'
    | '/api/cms/faqs'
    | '/api/cms/services'
    | '/api/cms/testimonials'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiCmsAboutRoute: typeof ApiCmsAboutRoute
  ApiCmsFaqsRoute: typeof ApiCmsFaqsRoute
  ApiCmsServicesRoute: typeof ApiCmsServicesRoute
  ApiCmsTestimonialsRoute: typeof ApiCmsTestimonialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cms/testimonials': {
      id: '/api/cms/testimonials'
      path: '/api/cms/testimonials'
      fullPath: '/api/cms/testimonials'
      preLoaderRoute: typeof ApiCmsTestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cms/services': {
      id: '/api/cms/services'
      path: '/api/cms/services'
      fullPath: '/api/cms/services'
      preLoaderRoute: typeof ApiCmsServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cms/faqs': {
      id: '/api/cms/faqs'
      path: '/api/cms/faqs'
      fullPath: '/api/cms/faqs'
      preLoaderRoute: typeof ApiCmsFaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cms/about': {
      id: '/api/cms/about'
      path: '/api/cms/about'
      fullPath: '/api/cms/about'
      preLoaderRoute: typeof ApiCmsAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  ApiContactRoute: ApiContactRoute,
  ApiCmsAboutRoute: ApiCmsAboutRoute,
  ApiCmsFaqsRoute: ApiCmsFaqsRoute,
  ApiCmsServicesRoute: ApiCmsServicesRoute,
  ApiCmsTestimonialsRoute: ApiCmsTestimonialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
